version: '3'
services:
    react:
        build: .
        container_name: trekmetrics-react
        restart: on-failure
        volumes:
            - .:/usr/src/app
            # - /usr/src/app/node_modules
        ports:
            - 3000:3000
